details:
  namespace: student80-bookinfo-uat
  image: ghcr.io/varotsk137/bookinfo-details
  tag: uat
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8080
  healthCheckPath: "/health"
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: bookinfo.uat.opsta.net
  path: "/student80/details(/|$)(.*)"
  serviceType: ClusterIP